# This workflow is run whenever a Pull Request is opened, re-opened, or taken
# out of draft (ready for review).
#
# NOTE: Due to the sensitive nature of this workflow, it must always be run
# against master AND with minimal permissions. These properties must always
# be maintained!
name: Assign
on: 
  pull_request_target:
    types: [assigned, opened, reopened, ready_for_review]

permissions:  
    pull-requests: write
    actions: none
    checks: none
    contents: none
    deployments: none
    issues: none
    packages: none
    repository-projects: none
    security-events: none
    statuses: none
jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    steps:
      - name: Event name 
        run: echo ${{ github.event_name}}
      # Checkout master branch of Teleport repository. This is to prevent an
      # attacker from submitting their own review assignment logic.
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: dev-workflow       
      - name: Installing the latest version of Go.
        uses: actions/setup-go@v2
      - name: Save reviewers in env 
        run: export REVS=$(cat <<EOF 
              "{\"*\":[\"russjones\", \"r0mant\"], \"joerger\":[\"zmb3\", \"atburke\"], \"fspmarshall\":[\"rosstimothy\", \"codingllama\"], \"xacrimon\":[\"zmb3\", \"joerger\"], 
              \"quinqu\":[\"timothyb89\", \"tcsc\"], \"timothyb89\":[\"codingllama\", \"xacrimon\"], \"tcsc\":[\"nklaassen\", \"codingllama\"], \"nklaassen\":[\"smallinsky\", \"tcsc\"], 
              \"r0mant\":[\"smallinsky\", \"timothyb89\"], \"smallinsky\":[\"joerger\", \"r0mant\"], \"codingllama\":[\"rosstimothy\", \"quinqu\"],
              \"rosstimothy\":[\"r0mant\", \"fspmarshall\"], \"zmb3\":[\"rosstimothy\", \"xacrimon\"], \"atburke\":[\"nklaassen\", \"fspmarshall\"]}"
              EOF
            )
      - run: echo $REVS
      # Run "assign-reviewers" subcommand on bot.
      - name: Assigning reviewers 
        run: cd .github/workflows/ci && go run cmd/main.go --token=${{ secrets.GITHUB_TOKEN }}  --reviewers=${{env.REVS}} assign-reviewers

      