on: 
  pull_request_target: 
    paths-ignore: '.github/workflows/**'
  
jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    steps:
        # Check out master branch
      - name: Check out branch 
        uses: actions/checkout@master
        # Install Go  
      - name: Installing Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.15.13'
      - name: Creating directories
        run: sudo mkdir -p $GOPATH/github/google
      - name: Installing Go-github
        run: git clone https://github.com/google/go-github.git $GOPATH/src/github/google
      - name: Updating dependencies...
        run: sudo cd $GOPATH/src/github/google/go-github && go get -u -v ./... 
        # Run command
      - name: Assigning reviewers 
        run: go run .github/workflows/bot.go assign-reviewers
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GO111MODULE: auto

      


