on: 
  pull_request_target: 
    paths-ignore: '.github/workflows/**'
  
jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    steps:
        # Install Go  
      - name: Installing Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.15.13'
      - name: Installing Go-github
        run: go get github.com/google/go-github/v36
        # Run command
      - name: Assigning reviewers 
        run: go run .github/workflows/bot.go assign-reviewers
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      


