name: Assign External
on: 
  schedule:
    # Runs every 30 minutes
    - cron:  '* * * * *' 
jobs:
  auto-request-review-external:
    name: Auto Request Review External
    if: ${{ github.event.pull_request.head.repo.full_name != 'gravitational/gh-actions-poc' }}
    runs-on: ubuntu-latest
    steps:
      # Checkout master branch of Teleport repository. This is to prevent an
      # attacker from submitting their own review assignment logic.
      - name: Checkout master branch
        uses: actions/checkout@master        
      - name: Installing the latest version of Go.
        uses: actions/setup-go@v2
      # Run "assign-reviewers" subcommand on bot.
      - name: Assigning reviewers 
        run: cd tool/ci && go run cmd/bot.go --token=${{ secrets.GITHUB_TOKEN }} --reviewers="{\"\":[\"quinqu\"]}" assign-reviewers-external