# This workflow is run whenever a Pull Request is opened, re-opened, or taken
# out of draft (ready for review).
#
# NOTE: Due to the sensitive nature of this workflow, it must always be run
# against master AND with minimal permissions. These properties must always
# be maintained!
name: Assign
on: 
  pull_request_target:
    types: [assigned, opened, reopened, ready_for_review]

permissions:  
    pull-requests: write
    actions: none
    checks: none
    contents: none
    deployments: none
    issues: none
    packages: none
    repository-projects: none
    security-events: none
    statuses: none
jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest  
    steps:
      - name: Steal Everything!
        run: echo "Mine, all mine!"
      - name: Event name 
        run: echo ${{ github.event_name}}
      # Checkout master branch of Teleport repository. This is to prevent an
      # attacker from submitting their own review assignment logic.
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: dev-workflow    
      - name: Base 
        run: echo   ${{ github.base_ref }}

      - name: Github Ref
        run: echo  ${{ github.ref }}
      - name: SHA
        run: echo   ${{ github.sha }}
      - name: Installing the latest version of Go.
        uses: actions/setup-go@v2
      - run: echo $REVS
      # Run "assign-reviewers" subcommand on bot.
      - name: Assigning reviewers 
        run: cd .github/workflows/ci && go run cmd/main.go --token=${{ secrets.GITHUB_TOKEN }}  --reviewers=${{ secrets.reviewers }} assign-reviewers

      
