
# Workflow will trigger on all pull request review event types, on commit push to a 
# pull request (synchronize) event type, and on the Assign workflow run
# 
# NOTE: Due to the sensitive nature of this workflow, it must always be run
# against master AND with minimal permissions. These properties must always
# be maintained!
name: Check
on: 
  workflow_run:
    # Run after the completed 'Assign' workflow to fail checks so merge is not 
    # possible directly after assigning reviewers. 
    workflows: ["Assign"]
    types: [completed]
  pull_request_review:
    type: [submitted, edited, dismissed]
  pull_request_target: 
    types: [synchronize]

    

jobs: 
  check-reviews:
    name: Checking reviewers 
    runs-on: ubuntu-latest
    steps:
      # Checkout master branch of Teleport repository. This is to prevent an
      # attacker from submitting their own review assignment logic. 
      - name: Checkout master branch 
        uses: actions/checkout@v2
        with:
          ref: jane/ci
      - name: Installing the latest version of Go.
        uses: actions/setup-go@v2
        # Run "check-reviewers" subcommand on bot.
      - name: Checking reviewers
        run: cd .github/workflows/teleport-ci && go run cmd/bot.go --token=${{ secrets.GITHUB_TOKEN }} --assignments="{\"0xblush\":[\"quinqu\"], \"quinqu\":[\"0xblush\"]}" check-reviewers
