# Workflow will trigger on all pull request review event types
on: pull_request_review

jobs: 
  check-reviews:
    name: Checking reviewers 
    runs-on: ubuntu-latest
    steps:
       # Check out base branch 
      - name: Check out branch 
        uses: actions/checkout@master
        # Install Go  
      - name: Installing Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.5'
        # Run command
      - name: Assigning reviewers 
        run: go run .github/workflows/bot.go check-reviewers
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
