
# Workflow will trigger on all pull request review event types, on commit push to a 
# pull request (synchronize) event type
# 
# NOTE: Due to the sensitive nature of this workflow, it must always be run
# against master AND with minimal permissions. These properties must always
# be maintained!
name: Check
on: 
  pull_request_review:
    type: [submitted, edited, dismissed]
    paths-ignore: 
      - '.github/workflows/**'
  pull_request_target: 
    types: [assigned, opened, reopened, ready_for_review, synchronize]
    paths-ignore: 
      - '.github/workflows/**'

jobs: 
  check-reviews:
    name: Checking reviewers 
    runs-on: ubuntu-latest
    steps:
      # Checkout master branch of Teleport repository. This is to prevent an
      # attacker from submitting their own review assignment logic. 
      - name: Checkout master branch 
        uses: actions/checkout@master
      - name: Installing the latest version of Go.
        uses: actions/setup-go@v2
        # Run "check-reviewers" subcommand on bot.
      - name: Checking reviewers
        run: cd .github/workflows/teleport-ci && go run cmd/bot.go --token=${{ secrets.GITHUB_TOKEN }} --default-reviewers="[quinqu, 0xblush]" --reviewers="{\"0xblush\":[\"quinqu\"], \"quinqu\":[\"0xblush\"]}" check-reviewers
