on: 
  push: 
    paths:
      - '.github/workflows/**'

jobs: 
  check-reviews:
    name: Checking reviewers 
    runs-on: ubuntu-latest
    steps:
       # Check out base branch 
      - name: Check out branch 
        uses: actions/checkout@master
        # Install Go  
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.5'
        # Run command
      - name: Invalidating reviews 
        run: go run .github/workflows/bot.go dismiss-reviewers
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
