name: GPG
on: 
  push:


jobs:
  test:
    name: GPG test
    runs-on: ubuntu-latest
    steps:
      - name: Event name 
        run: echo ${{ github.event_name}}
      - name: Checkout master branch
        uses: actions/checkout@master
      - name: Check if GPG is installed 
        run: gpg --help 
      - name: Curl key
        run: curl https://github.com/web-flow.gpg >> github.pgp
      - name: Import key 
        run: gpg --import github.pgp 
      - name: ls 
        run: ls .github/workflows/
      - name: check for temp dir 
        run: ls /tmp
      - name: verify commit 
        run: gpg --verify .github/workflows/test.sig .github/workflows/data.txt

      