name: GPG
on: 
  push:


jobs:
  test:
    name: GPG test
    runs-on: ubuntu-latest
    steps:
      - name: Event name 
        run: echo ${{ github.event_name}}
      - name: Check if GPG is installed 
        run: gpg --help 
      - name: Curl key
        run: curl https://github.com/web-flow.gpg >> github.pgp
      - name: Import key 
        run: gpg --import github.pgp 
  
      - name: Run gpg --list-keys
        run: gpg --list-keys 
      - name: verify commit 
        run: gpg --verify .github/workflows/test.sig .github/workflows/data.txt

      