name: GPG
on: 
  push:


jobs:
  test:
    name: GPG test
    runs-on: ubuntu-latest
    steps:
      - name: Event name 
        run: echo ${{ github.event_name}}
      - name: Check if GPG is installed 
        run: gpg --help 
      - name: Run gpg --list-keys
        run: gpg --list-keys 

      