name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
 job01:
   if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
   runs-on: [ubuntu-latest]
   steps:
      - name: Event name 
        run: echo ${{ github.event_name}}
      # Checkout master branch of Teleport repository. This is to prevent an
      # attacker from submitting their own review assignment logic.
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: dev-workflow       
      - name: Installing the latest version of Go.
        uses: actions/setup-go@v2
      - name: Checking for run approval 
        run: cd tool/ci && go run cmd/bot.go --token=${{ secrets.GITHUB_TOKEN }}  --reviewers="{\"\":[\"quinqu\"], \"quinqu\":[\"0xblush\"]}" check-run-approval
      